# Generated by Django 4.2.4 on 2023-08-28 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='files',
            name='tag',
            field=models.CharField(default='common', max_length=100),
        ),
    ]
