# Generated by Django 4.2.2 on 2023-08-28 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_files_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='files',
            name='year',
            field=models.CharField(default='2021', max_length=4),
            preserve_default=False,
        ),
    ]
