# Generated by Django 4.1.6 on 2023-08-30 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_files_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='files',
            name='tag',
            field=models.CharField(choices=[('2021', 2021), ('2020', 2020), ('2022', 2022), ('2023', 2023)], default='common', max_length=100),
        ),
    ]
