# Generated by Django 4.1.6 on 2023-08-30 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_files_tag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='files',
            name='tag',
            field=models.CharField(default='common', max_length=100),
        ),
        migrations.AlterField(
            model_name='files',
            name='year',
            field=models.CharField(choices=[('2020', 2020), ('2021', 2021), ('2022', 2022), ('2023', 2023)], max_length=4),
        ),
    ]
