# Generated by Django 4.1.6 on 2023-08-30 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_files_tag_alter_files_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='files',
            name='block',
            field=models.CharField(choices=[('1 блок', 1), ('2 блок', 2)], default='1 блок', max_length=10),
            preserve_default=False,
        ),
    ]
