# Generated by Django 4.1.6 on 2023-08-30 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_files_block'),
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('middle_name', models.CharField(max_length=255)),
                ('birth_date', models.DateField()),
                ('education', models.CharField(max_length=1000)),
                ('diploma', models.FileField(upload_to='diplomas/')),
                ('qualification', models.CharField(max_length=255)),
                ('position', models.CharField(max_length=255)),
                ('experience', models.CharField(max_length=255)),
                ('overall_experience', models.CharField(max_length=255)),
                ('category', models.CharField(max_length=255)),
                ('phone_number', models.CharField(max_length=12)),
                ('image', models.ImageField(upload_to='avatars/')),
            ],
        ),
        migrations.RenameModel(
            old_name='Files',
            new_name='File',
        ),
    ]
