# Generated by Django 4.2.2 on 2023-08-30 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_alter_teacher_diploma'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='block',
            field=models.CharField(choices=[('1', '1 блок'), ('2', '2 блок')], max_length=10),
        ),
        migrations.AlterField(
            model_name='file',
            name='year',
            field=models.CharField(choices=[('2020-2021', '2020-2021'), ('2021-2022', '2021-2022'), ('2022-2023', '2022-2023')], max_length=10),
        ),
    ]
