# Generated by Django 4.1.6 on 2023-09-01 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_alter_teacher_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='block',
            field=models.CharField(choices=[('1', '1'), ('2', '2')], max_length=10),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='block',
            field=models.IntegerField(choices=[('1', '1'), ('2', '2')], max_length=10),
        ),
    ]
