# Generated by Django 4.1.6 on 2023-09-01 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_alter_file_block_alter_teacher_block'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='block',
            field=models.CharField(choices=[('1', '1'), ('2', '2')], max_length=10),
        ),
    ]
