# Generated by Django 4.2.4 on 2023-09-02 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_alter_file_tag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='name',
            field=models.CharField(max_length=2550),
        ),
        migrations.AlterField(
            model_name='file',
            name='tag',
            field=models.CharField(choices=[('schedule', 'schedule'), ('course', 'course'), ('methodist_cyclogram', 'methodist_cyclogram'), ('mad', 'mad'), ('methodist_monitoring', 'methodist_monitoring'), ('personal_development_map', 'personal_development_map'), ('monitoring', 'monitoring'), ('group_cyclogram', 'group_cyclogram'), ('year_plan', 'year_plan'), ('gpp', 'gpp'), ('about', 'about')], default='common', max_length=100),
        ),
    ]
