# Generated by Django 4.1.6 on 2023-09-02 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_alter_file_file_alter_file_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='block',
            field=models.CharField(choices=[('1', '1 блок'), ('2', '2 блок')], max_length=10),
        ),
        migrations.AlterField(
            model_name='file',
            name='tag',
            field=models.CharField(choices=[('schedule', 'Кесте'), ('course', 'Курс'), ('methodist_cyclogram', 'Әдіскер циклограмасы'), ('mad', 'МАД'), ('methodist_monitoring', 'Әдіскер мониторинг'), ('personal_development_map', 'Жеке даму картасы'), ('monitoring', 'Мониторинг'), ('group_cyclogram', 'Топтың циклограммасы'), ('year_plan', 'Жалдық жоспар'), ('gpp', 'Топтардың перспективалық жоспарлары'), ('about', 'Біз туралы')], default='common', max_length=100),
        ),
        migrations.AlterField(
            model_name='file',
            name='year',
            field=models.CharField(choices=[('2020-2021', '2020-2021'), ('2021-2022', '2021-2022'), ('2022-2023', '2022-2023'), ('2023-2024', '2023-2024')], max_length=10),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='block',
            field=models.CharField(choices=[('1', '1 блок'), ('2', '2 блок')], max_length=10),
        ),
    ]
